### PR TITLE
Plot serial intervals

### PR DESCRIPTION
**Pull request by FarmHJ**

### CODE REVIEW

**Comment by FarmHJ** [comment]
Addressing #168

**Review by rcw5890 — COMMENTED** [review]
Thanks @FarmHJ , this looks like exactly what we need.
I know we were talking about this yesterday. Just to remind myself:
- [x] Make the lines somewhat transparent
- [x] Use "Probability" for the y label
- [x] Use "Day" for the x label

**Review by rcw5890 — CHANGES_REQUESTED** [review]
Very nice, thanks for making those changes @FarmHJ 
However, I think we should normalize the serial intervals after loading them from the file. The discretization method only yields normalized values if you include a nonzero w_0 term, while we are always setting w_0=0. For most serial interval samples this w_0 is much less than 1%, so it will not be perceptible in the figure, but I think it's worth doing so that the method is fully correct.

Also, what do you think of plotting `serial_intervals[i,:26]` instead so that the ends of the lines are even with the final day 25 tick?

**Comment by FarmHJ** [comment]
> Very nice, thanks for making those changes @FarmHJ
> However, I think we should normalize the serial intervals after loading them from the file. The discretization method only yields normalized values if you include a nonzero w_0 term, while we are always setting w_0=0. For most serial interval samples this w_0 is much less than 1%, so it will not be perceptible in the figure, but I think it's worth doing so that the method is fully correct.
> 
> Also, what do you think of plotting `serial_intervals[i,:26]` instead so that the ends of the lines are even with the final day 25 tick?

I don't fully understand how to normalise the serial intervals. Nevertheless, I've tried normalising it. I divide the entry in each row by its sum, doing it only on the time period we are interested in.

**Comment by rcw5890** [comment]
> I don't fully understand how to normalise the serial intervals. Nevertheless, I've tried normalising it. I divide the entry in each row by its sum, doing it only on the time period we are interested in.

I'm actually thinking to normalize the full 60 day serial intervals from the file (what the BranchProPosterior does). The values truncated to the 25 day plotting window will be slightly unnormalized, but that's okay as the probabilities we are plotting are still correct. So something like:
`serial_intervals = serial_intervals / np.sum(serial_intervals, axis=1)[:,np.newaxis]`

On this subject, I suspect there's something out of date about the serial intervals csv file currently in the repository. In this PR, can you add a call of np.random.seed to the beginning of the write_ser_int_data function in data_library/serial_interval/parse_data_si.py, then rerun that file and commit the new csv as well?

**Review by rcw5890 — CHANGES_REQUESTED** [review]
Looks great! Let's just add a number (any number) as the argument of np.random.seed. The default seed varies based on time and system, so without an argument it will not be consistent if we run it later.

**Review by rcw5890 — APPROVED** [review]

**Pull request merged**
